samples/ASP.NET.Sample/Pages/ClientArea.cshtml.cs
using Samples.Shared.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenAPI.Net.Auth;
using System.Collections.Generic;
using System.Linq;
using System.Reactive.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace ASP.NET.Sample.Pages
{
    public class ClientAreaModel : PageModel
    {
        private readonly ITradingAccountsService _accountsService;

        public ClientAreaModel(ITradingAccountsService accountsService)
        {
            _accountsService = accountsService;
        }

        public Token Token { get; private set; }

        public List<ProtoOACtidTraderAccount> Accounts { get; } = new();

        [BindProperty(SupportsGet = true)]
        public long AccountLogin { get; set; }

        public async Task OnGetAsync()
        {
            if (!TempData.TryGetValue("Token", out var tokenJson)) return;

            TempData.Remove("Token");

            Token = JsonSerializer.Deserialize<Token>(tokenJson.ToString());

            Accounts.AddRange(await _accountsService.GetAccounts(Token.AccessToken));

            var selectedAccount = Accounts.FirstOrDefault();

            if (selectedAccount is not null)
            {
                AccountLogin = selectedAccount.TraderLogin;
            }
        }
    }
}

samples/ASP.NET.Sample/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace ASP.NET.Sample.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

samples/ASP.NET.Sample/Pages/Index.cshtml.cs
using Samples.Shared.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenAPI.Net.Auth;
using System;
using System.Text.Json;
using System.Threading.Tasks;

namespace ASP.NET.Sample.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ApiCredentials _apiCredentials;

        public IndexModel(ApiCredentials apiCredentials)
        {
            _apiCredentials = apiCredentials;
        }

        public App App => new(_apiCredentials.ClientId, _apiCredentials.Secret, $"{(Request.IsHttps ? "https" : "http")}://{Request.Host}{Request.Path}");

        public ActionResult OnGetAddAccount()
        {
            return Redirect(App.GetAuthUri().ToString());
        }

        public async Task<ActionResult> OnGetAsync([FromQuery] string code)
        {
            if (string.IsNullOrWhiteSpace(code)) return null;

            try
            {
                var token = await TokenFactory.GetToken(code, App);

                TempData["Token"] = JsonSerializer.Serialize(token);

                return RedirectToPage("ClientArea");
            }
            catch (Exception ex)
            {
                TempData["Exception"] = JsonSerializer.Serialize(ex);

                return RedirectToPage("Error");
            }
        }
    }
}

samples/ASP.NET.Sample/Pages/Index.cshtml
@page
@model IndexModel
<div tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Authentication</h5>
            </div>
            <div class="modal-body">
                <p>Please click on Add Trading Account(s) button</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" asp-page="Index" asp-page-handler="addaccount">Add Trading Account(s)</a>
            </div>
        </div>
    </div>
</div>

samples/ASP.NET.Sample/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Open API.NET Web App Demo</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js" asp-append-version="true"></script>
</head>
<body class="container-fluid bg-dark">
    @RenderBody()

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>